= Data streaming and event stream processing
:page-layout: landing
:data-uri:

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++
<div class="lg:row-span-2 flex flex-col items-start gap-4 rounded border p-4">

  <div class="rounded bg-level1 p-2">
      svg:ROOT:what-is-astra-db.svg[role="mx-auto my-auto w-8 h-8"]
  </div>

  <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Streaming Learning</h3></div>

  Learn about the amazing things you can do with all of our streaming products.
  We've included best practices for Apache Pulsar, a full connector reference,
  and examples for getting the most out of Astra's CDC feature.

  xref:streaming-learning:use-cases-architectures:real-time-data-pipeline/index.adoc[Build a real-time data pipeline]

</div>

<div class="grid lg:grid-rows-1 lg:grid-cols-2 gap-6 mt-6">

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 flex p-2">
        svg:ROOT:using-the-astra-console.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Astra Streaming</h3>

    Delivered as a fully-managed SaaS with boundless scale, massive throughput and low latency,
    Astra Streaming is the simplest way to modernize your event driven architecture and turbo charge your data in motion strategy.

    xref:astra-streaming:getting-started:index.adoc[Astra Streaming quickstat]

  </div>

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 flex p-2">
      svg:ROOT:what-is-datastax-luna.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <h3 class="discrete !text-h2 !m-0 [&>a]:text-white">IBM Elite Support for Apache Pulsar</h3>

    A production-ready distribution of Apache Pulsar with 24/7 expert enterprise support.

    https://www.ibm.com/docs/en/supportforpulsar[Learn more]

  </div>

</div>

<div class="lg:row-span-2 flex flex-col items-start gap-4 rounded border p-4 mt-6">

  <div class="rounded bg-level1 p-2">
      svg:ROOT:avoid-cloud-lockin.svg[role="mx-auto my-auto w-8 h-8"]
  </div>

  <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">KAAP Operator</h3></div>

  The Kubernetes Autoscaler for Apache Pulsar (KAAP) simplifies
  running Apache Pulsar on Kubernetes by applying the familiar operator pattern
  to Pulsar's components, and horizonally scaling resources up or down based on
  CPU and memory workloads.

  xref:kaap-operator::index.adoc[Learn more about KAAP]

</div>

<div class="grid lg:grid-rows-1 lg:grid-cols-3 gap-6 mt-6">

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 p-2">
        svg:ROOT:connect-clients-to-astra-db.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Sink and source connectors</h3></div>

    Pulsar supports many popular streaming connectors, including:

    <ul class="!m-0 [&>li]:my-2">
      <li>xref:streaming-learning:pulsar-io:connectors/sinks/elastic-search.adoc[]</li>
      <li>xref:streaming-learning:pulsar-io:connectors/sinks/kafka.adoc[]</li>
      <li>xref:streaming-learning:pulsar-io:connectors/sinks/snowflake.adoc[]</li>
      <li>xref:streaming-learning:pulsar-io:connectors/index.adoc[And more]</li>
    </ul>

  </div>

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 p-2">
        svg:ROOT:migrating-apps.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Starlight API integrations</h3></div>

    Learn about the Starlight API suite to painlessly integrate existing messaging workloads.

    <ul class="!m-0 [&>li]:my-2">
      <li>xref:starlight-for-jms::index.adoc[Starlight for JMS]</li>
      <li>xref:starlight-for-kafka::index.adoc[]</li>
      <li>xref:starlight-for-rabbitmq::index.adoc[]</li>
    </ul>

  </div>

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 p-2">
        svg:ROOT:what-is-astra-streaming.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">xref:astra-streaming:developing:astream-cdc.adoc[Change Data Capture]</h3></div>

    Change Data Capture (CDC) for Astra Streaming enables you to send data
    changes in real time throughout your entire ecosystem.  With a wide range of
    connectors to data warehouses, messaging systems, data lakes as well as client
    libraries, you can send your data wherever it needs to go in real time.

    xref:astra-streaming:developing:astream-cdc.adoc[]

  </div>

</div>

++++