= Data Generator
:connectorType: data-generator

Use the Data Generator source connector for testing purposes.

The Data Generator source connector uses the https://github.com/Codearte/jfairy[jFairy library] to stream sample messages to a {pulsar-short} topic.
The sample messages contain simulated `Person` data with fields like `firstName`, `email`, and `telephoneNumber`.

The connector generates data continuously while it is running.
There is no upper limit on the number of messages it can generate.

[#compatibility]
== Compatibility

{product} supports {pulsar-reg} {pulsar-version}, which uses version 0.5.9 of the jFairy library.

For the `Person()` class specification, see the https://github.com/apache/pulsar/blob/branch-{pulsar-version}/pulsar-io/data-generator/src/main/java/org/apache/pulsar/io/datagenerator/Person.java[{pulsar} GitHub repository].

== Create the connector

include::pulsar-io:partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sources/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sources/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} source connector properties

include::pulsar-io:partial$connectors/sources/pulsar-config-params.adoc[]

[#configs]
=== Data Generator source connector properties (`configs`)

In the `configs` section of the connector configuration, the only available property is `sleepBetweenMessages`.
This property sets the delay between messages generated by the connector.
The default value is `50` milliseconds.
For an uninterrupted stream of messages, set this property to `0`.