= Data Generator
:connectorType: data-generator

The Data generator source connector produces messages for testing and persists the messages to {pulsar-short} topics.

The Data Generator source connector creates fake data on an {pulsar-reg} topic using the https://github.com/Codearte/jfairy[JFAIRY library] to generate a message containing "person" data.

"Person" data includes first and last name, home address, and email address, among other details.

The connector will produce data indefinitely while it is running.

{product} currently supports {pulsar} {pulsar-version}, which uses version 0.5.9 of the jfairy library.

For a reference of the full "Person" class, https://github.com/apache/pulsar/blob/branch-{pulsar-version}/pulsar-io/data-generator/src/main/java/org/apache/pulsar/io/datagenerator/Person.java[view the source].

== Create the connector

include::partial$connectors/sources/get-started.adoc[]

include::partial$connectors/sources/manage.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Data Generator (`configs`)

These values are provided in the "configs" area.

[%header,format=csv,cols="2,1,1,3"]
|===
"Name","Required","Default","Description"
"sleepBetweenMessages ","false","50","How many seconds to sleep between emitting messages"
|===
