:connectorName: data-gen-src
:connectorType: data-generator
:attribute-missing: skip
:slug: data-generator-source-connector
:page-tag: data-generator,source-connector

= Data Generator Source Connector for {product_name}

The Data Generator source connector creates fake data on an Apache Pulsar topic using the https://github.com/Codearte/jfairy[JFAIRY library] to generate a message containing "person" data. 

"Person" data includes first and last name, home address, and email address, among other details.

The connector will produce data indefinitely while it is running.

Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses version 0.5.9 of the jfairy library.

For a reference of the full "Person" class, https://github.com/apache/pulsar/blob/branch-{pulsar_version}/pulsar-io/data-generator/src/main/java/org/apache/pulsar/io/datagenerator/Person.java[view the source^].

== Get Started

include::partial$connectors/sources/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sources/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sources/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/astra.csv[]
|===

=== Data Generator (configs)

These values are provided in the "configs" area.

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/{connectorType}/config.csv[]
|===
