= Debezium Oracle
:connectorType: debezium-oracle

The Debezium Oracle source connector reads data from Debezium Oracle systems and produces data to {pulsar-short} topics.

Debezium’s Oracle connector captures and records row-level changes that occur in databases on Oracle servers, including tables that are added while the connector is running.

The connector can be configured to emit change events for specific subsets of schemas and tables, or to ignore, mask, or truncate values in specific columns.

[#compatibility]
== Compatibility

include::pulsar-io:partial$connectors/sources/debezium-compatibility.adoc[]

== Create the connector

include::pulsar-io:partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sources/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sources/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} source connector parameters

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium Oracle source connector parameters (`configs`)

The {product} Oracle source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium-version}/connectors/mysql.html#oracle-connector-properties[Debezium Oracle connector properties] for a complete list.

== What's next?

For more on Debezium's Oracle connector, see the https://debezium.io/documentation/reference/{debezium-version}/connectors/oracle.html[Debezium documentation].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-oracle[{pulsar} Oracle documentation].


