= Debezium MySQL
:connectorName: debezium-mysql-src
:connectorType: debezium-mysql
:page-tag: mysql,debezium,cdc,source-connector

The Debezium MySQL connector reads the binlog, produces change events for row-level INSERT, UPDATE, and DELETE operations, and emits these change events as messages in an {pulsar-reg} topic.

{product} currently supports {pulsar} {pulsar-version}, which uses Debezium {debezium-version} libraries.

== Get Started

include::partial$connectors/sources/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sources/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sources/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== {product}

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/astra.csv[]
|===

=== Debezium MySQL (configs)

These values are provided in the "configs" area.

The {product} MySQL source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium-version}/connectors/mysql.html#mysql-connector-properties[Debezium MySQL connector properties] for a complete list.

== What's next?

For a list of supported MySQL versions, see the https://debezium.io/releases/{debezium-version}/[Debezium documentation].

For a detailed explanation of Debezium's MySQL connector, see the https://debezium.io/documentation/reference/{debezium-version}/connectors/mysql.html[Debezium documentation].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-mysql[{pulsar} MySQL documentation].

