= Debezium SQL Server
:connectorName: debezium-mssql-src
:connectorType: debezium-sqlserver
:page-tag: sql-server,cdc,debezium,source-connector

The Debezium SQL Server connector is based on the change data capture feature available in SQL Server 2016 Service Pack 1 (SP1) and later editions.

The SQL Server capture process monitors designated databases and tables and stores changes into specifically created change tables with stored procedure facades.

{product} currently supports {pulsar-reg} {pulsar-version}, which uses Debezium {debezium-version} libraries. For a list of supported SQL Server versions, please refer to the
https://debezium.io/releases/{debezium-version}/[Debezium documentation].

== Get Started

To create a Debezium SQL Server source connector, do the following.
Your deployment's values may differ.

. Create an Azure SQL Server named `kalash-server-stream672` with a database `cdc_test`, containing the table `dbo.accounts`.
. Name your connector `dbz-stream672`.
. Create the required topics under the namespace `kalash-stream672/default`, following the correct Debezium naming conventions.

  * `<connector_name>-debezium-history-topic`
  * `<connector_name>-debezium-offset-topic`
  * `<server_name>`
  * `<server_name>.<dbname>.<tablename>`

These topics must be created manually, as topic autocreation is not available.
Data should be consumed from the `events` topic.
The `topic.prefix` configuration value must match `database.server.name`. In this configuration, both are set to `kalash-server-stream672`.

Ensure `task.id` is passed as a string (`"0"`), not an integer (0), otherwise the connector will throw a `NullPointerException`.

For more on Debezium topic naming conventions, refer to the https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#sqlserver-topic-names[Debezium documentation].

include::partial$connectors/sources/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sources/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sources/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== {product}

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/astra.csv[]
|===

=== Debezium SQL Server (configs)

These values are provided in the "configs" area.

The {product} SQL Server source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium-version}/connectors/sqlserver.html#sqlserver-connector-properties[Debezium SQL Server connector properties] for a complete list.

== What's next?

For more on Debezium's SQL Server connector, see the https://debezium.io/documentation/reference/{debezium-version}/connectors/sqlserver.html[the Debezium documentation].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-microsoft-sql[{pulsar} SQL Server documentation].