= Debezium PostgreSQL
:connectorType: debezium-postgres

The Debezium PostgreSQL source connector produces a change event for every row-level `INSERT`, `UPDATE`, and `DELETE` operation that it captures, and then it sends change event records for each table to separate {pulsar-short} topics.

[#compatibility]
== Compatibility

include::pulsar-io:partial$connectors/sources/debezium-compatibility.adoc[]

== Create the connector

include::pulsar-io:partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sources/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sources/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} source connector parameters

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium PostgreSQL source connector parameters (`configs`)

Set these parameters in the `configs` section of the connector configuration.

Supported parameters include all properties provided in the https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-connector-properties[Debezium connector for PostgreSQL] and the https://pulsar.apache.org/docs/io-debezium-source[OSS {pulsar} Debezium source connector] with the exception of properties that aren't available in the <<compatibility,supported Debezium and {pulsar-short} libraries>>.