= Debezium MySQL
:connectorType: debezium-mysql

The Debezium MySQL source connector reads the `binlog` from MySQL database servers, produces change events for row-level `INSERT`, `UPDATE`, and `DELETE` operations, and then sends change event messages to {pulsar-short} topics.

[#compatibility]
== Compatibility

include::pulsar-io:partial$connectors/sources/debezium-compatibility.adoc[]

== Create the connector

include::pulsar-io:partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sources/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sources/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} source connector properties

include::pulsar-io:partial$connectors/sources/pulsar-config-params.adoc[]

[#configs]
=== Debezium MySQL source connector properties (`configs`)

Set these properties in the `configs` section of the connector configuration.

Generally, all properties provided in the https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-connector-properties[Debezium connector for MySQL] and the https://pulsar.apache.org/docs/io-debezium-source[OSS {pulsar} Debezium source connector] are supported.
Exceptions include properties that aren't relevant to {product} and properties that are only present in <<compatibility,incompatible versions>>.