= Debezium SQL Server
:connectorType: debezium-sqlserver

The https://debezium.io/documentation/reference/stable/connectors/sqlserver.html[Debezium SQL Server source connector] reads data from Debezium SQL Server systems and produces data to {pulsar-short} topics.
It is based on the change data capture (CDC) feature available in SQL Server 2016 Service Pack 1 (SP1) and later editions.

The SQL Server capture process monitors designated databases and tables, and then stores changes into dedicated change tables with stored procedure facades.

[#compatibility]
== Compatibility

include::pulsar-io:partial$connectors/sources/debezium-compatibility.adoc[]

[#create-the-connector]
== Create the connector

To create a Debezium SQL Server source connector, you must prepare your SQL Server instance and {pulsar-short} topics before creating the connector:

. If you don't already have one, create an Azure SQL Server or other compatible SQL Server instance, and then create a database and table to capture changes from.

. In your {pulsar-short} namespace, create the following required topics according to the https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#sqlserver-topic-names[Debezium topic naming conventions]:
+
* `**CONNECTOR_NAME**-debezium-history-topic`
* `**CONNECTOR_NAME**-debezium-offset-topic`
* `**SERVER_NAME**`
* `**SERVER_NAME**.**DB_NAME**.**TABLE_NAME**`

+
Replace the following:
--
* `**CONNECTOR_NAME**`: The name that you want to use for your Debezium SQL Server source connector.
* `**SERVER_NAME**`: The name of your SQL Server instance.
* `**DB_NAME**`: The name of the database you are capturing changes from.
* `**TABLE_NAME**`: The name of the table you are capturing changes from.

[IMPORTANT]
====
You must create these topics manually, and the topic names must conform to the Debezium naming conventions.

{product} cannot create the topics automatically.
====
--

. When you create the source connector, make sure the following `<<configs,configs>>` parameters are set correctly:
+
* The `topic.prefix` and `database.server.name` value must be the same.
* The `task.id` value must be a string (`"task.id": "0"`), not an integer (`"task.id": 0`).
If `task.id` is an integer, the connector throws a `NullPointerException`.

. Set your consumers to subscribe to the `events` topic in your {pulsar-short} namespace to receive CDC events.
This topic contains the CDC events emitted by Debezium for the configured tables.

include::pulsar-io:partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sources/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sources/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} source connector parameters

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium SQL Server source connector parameters (`configs`)

[IMPORTANT]
====
Make sure you set `topic.prefix`, `database.server.name`, and `task.id` correctly, as explained in <<create-the-connector>>.
====

The {product} Debezium SQL Server source connector supports all https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#sqlserver-connector-properties[Debezium SQL Server connector properties] that are available in the <<compatibility,supported Debezium libraries>>.

For the OSS {pulsar-short} connector's properties and more configuration examples, see the https://pulsar.apache.org/docs/io-debezium-source[{pulsar} Debezium source connector documentation].

Set these properties in the `configs` section of the connector configuration.