= Debezium MongoDB
:connectorType: debezium-mongodb

The Debezium MongoDB source connector reads data from Debezium MongoDB systems and produces data to {pulsar-short} topics.

Debezium’s MongoDB connector tracks a MongoDB replica set or a MongoDB sharded cluster for document changes in databases and collections and records those changes as messages in an {pulsar-reg} topic.

The connector automatically handles the addition or removal of shards in a sharded cluster, changes in membership of each replica set, elections within each replica set, and the resolution of communications problems.

{product} currently supports {pulsar} {pulsar-version}, which uses Debezium {debezium-version} libraries. For a list of supported MongoDB versions, please refer to the https://debezium.io/releases/{debezium-version}/[Debezium documentation].

== Create the connector

include::partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::partial$connectors/sources/edit.adoc[]

== Manage the connector

include::partial$connectors/sources/manage.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium MongoDB (`configs`)

These values are provided in the "configs" area.

[%header,format=csv,cols="2,1,1,3"]
|===
"Name","Required","Default","Description"
"database.whitelist","true","","A list of all databases hosted by this server which is monitored by the connector. This is optional, and there are other properties for listing databases and tables to include or exclude from monitoring."
"mongodb.hosts","true","","The comma-separated list of hostname and port pairs ('host' or 'host:port') of the MongoDB servers in the replica set. If mongodb.members.auto.discover is set to false, prefix with the replica set name (e.g., rs0/localhost:27017)."
"mongodb.name","true","","A unique name that identifies the connector and/or MongoDB replica set or shared cluster that this connector monitors. Each server should be monitored by at most one Debezium connector."
"mongodb.password","true","","Password to be used when connecting to MongoDB. This is required only when MongoDB is configured to use authentication."
"mongodb.task.id","true","","The taskId of the MongoDB connector that attempts to use a separate task for each replica set."
"mongodb.user","true","","Name of the database user to be used when connecting to MongoDB. This is required only when MongoDB is configured to use authentication."
|===

== What's next?

For a detailed explanation of Debezium's MongoDB connector, read https://debezium.io/documentation/reference/{debezium-version}/connectors/mongodb.html[the Debezium documentation].

Learn more about Debezium's MongoDB connector in the https://pulsar.apache.org/docs/io-debezium-source/#example-of-mongodb[{pulsar} MongoDB documentation].
