= Debezium PostgreSQL
:connectorType: debezium-postgres

The Debezium PostgreSQL source connector reads data from Debezium PostgreSQL systems and produces data to {pulsar-short} topics.

The PostgreSQL connector produces a change event for every row-level insert, update, and delete operation that it captures, and sends change event records for each table in a separate {pulsar-reg} topic.

[#compatibility]
== Compatibility

include::pulsar-io:partial$connectors/sources/debezium-compatibility.adoc[]

== Create the connector

include::pulsar-io:partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sources/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sources/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} source connector parameters

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium PostgreSQL source connector parameters (`configs`)

These parameters are set in the `configs` section of the connector configuration.

The {product} PostgreSQL source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium-version}/connectors/postgresql.html#postgresql-connector-properties[Debezium PostgreSQL connector properties] for a complete list.

== What's next?

For more on Debezium's PostgreSQL connector, see the https://debezium.io/documentation/reference/{debezium-version}/connectors/postgresql.html[Debezium documentation].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-postgresql[{pulsar} PostgreSQL documentation].
