:connectorName: debezium-mssql-src
:connectorType: debezium-sqlserver
:attribute-missing: skip
:slug: sql-server-source-connector
:page-tag: sql-server,cdc,debezium,source-connector

= Debezium SQL Server Source Connector

The Debezium SQL Server connector is based on the change data capture feature available in SQL Server 2016 Service Pack 1 (SP1) and later editions. 

The SQL Server capture process monitors designated databases and tables and stores changes into specifically created change tables with stored procedure facades.

Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses Debezium {debezium_version} libraries. For a list of supported SQL Server versions, please refer to the
https://debezium.io/releases/{debezium_version}/[Debezium documentation^].

== Get Started

include::partial$connectors/sources/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sources/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sources/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/astra.csv[]
|===

=== Debezium SQL Server (configs)

These values are provided in the "configs" area.

The Astra Streaming SQL Server source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium_version}/connectors/sqlserver.html#sqlserver-connector-properties[Debezium SQL Server connector properties^] for a complete list.

== What's next?

For more on Debezium's SQL Server connector, see the https://debezium.io/documentation/reference/{debezium_version}/connectors/sqlserver.html[the Debezium documentation^].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-microsoft-sql[Apache Pulsar SQL Server documentation^].