:connectorName: debezium-mysql-src
:connectorType: debezium-mysql
:attribute-missing: skip
:slug: mysql-source-connector
:page-tag: mysql,debezium,cdc,source-connector

= Debezium MySQL Source Connector

The Debezium MySQL connector reads the binlog, produces change events for row-level INSERT, UPDATE, and DELETE operations, and emits these change events as messages in an Apache Pulsar topic.

Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses Debezium {debezium_version} libraries. 

== Get Started

include::partial$connectors/sources/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sources/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sources/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/astra.csv[]
|===

=== Debezium MySQL (configs)

These values are provided in the "configs" area.

The Astra Streaming MySQL source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium_version}/connectors/mysql.html#mysql-connector-properties[Debezium MySQL connector properties^] for a complete list.

== What's next?

For a list of supported MySQL versions, see the https://debezium.io/releases/{debezium_version}/[Debezium documentation^].

For a detailed explanation of Debezium's MySQL connector, see the https://debezium.io/documentation/reference/{debezium_version}/connectors/mysql.html[Debezium documentation^].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-mysql[Apache Pulsar MySQL documentation^].

