:connectorName: debezium-orcl-src
:connectorType: debezium-oracle
:attribute-missing: skip
:slug: oracle-source-connector
:page-tag: oracle,debezium,cdc,source-connector

= Debezium Oracle Source Connector

Debezium’s Oracle connector captures and records row-level changes that occur in databases on Oracle servers, including tables that are added while the connector is running. 

The connector can be configured to emit change events for specific subsets of schemas and tables, or to ignore, mask, or truncate values in specific columns.

{product_name} currently supports Apache Pulsar {pulsar_version}, which uses Debezium {debezium_version} libraries. 

== Get Started

include::partial$connectors/sources/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sources/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sources/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sources/astra.csv[]
|===

=== Debezium Oracle

The Astra Streaming Oracle source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium_version}/connectors/mysql.html#oracle-connector-properties[Debezium Oracle connector properties^] for a complete list.

== What's next?

For a list of supported Oracle versions, see the https://debezium.io/releases/{debezium_version}/[Debezium documentation^].

For more on Debezium's Oracle connector, see the https://debezium.io/documentation/reference/{debezium_version}/connectors/oracle.html[Debezium documentation^].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-oracle[Apache Pulsar Oracle documentation^].


