= Debezium PostgreSQL
:connectorType: debezium-postgres

The Debezium PostgreSQL source connector reads data from Debezium PostgreSQL systems and produces data to {pulsar-short} topics.

The PostgreSQL connector produces a change event for every row-level insert, update, and delete operation that it captures, and sends change event records for each table in a separate {pulsar-reg} topic.

{product} currently supports {pulsar} {pulsar-version}, which uses Debezium {debezium-version} libraries. For a list of supported PostgreSQL versions, please refer to the
https://debezium.io/releases/{debezium-version}/[Debezium documentation].

== Create the connector

include::partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::partial$connectors/sources/edit.adoc[]

== Manage the connector

include::partial$connectors/sources/manage.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium PostgreSQL (`configs`)

These values are provided in the "configs" area.

The {product} PostgreSQL source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium-version}/connectors/postgresql.html#postgresql-connector-properties[Debezium PostgreSQL connector properties] for a complete list.

== What's next?

For more on Debezium's PostgreSQL connector, see the https://debezium.io/documentation/reference/{debezium-version}/connectors/postgresql.html[Debezium documentation].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-postgresql[{pulsar} PostgreSQL documentation].
