= Debezium MySQL
:connectorType: debezium-mysql

The Debezium MySQL source connector reads data from Debezium MySQL systems and produces data to {pulsar-short} topics.

The Debezium MySQL connector reads the binlog, produces change events for row-level INSERT, UPDATE, and DELETE operations, and emits these change events as messages in an {pulsar-reg} topic.

{product} currently supports {pulsar} {pulsar-version}, which uses Debezium {debezium-version} libraries.

== Create the connector

include::partial$connectors/sources/get-started.adoc[]

== Edit the connector

include::partial$connectors/sources/edit.adoc[]

== Manage the connector

include::partial$connectors/sources/manage.adoc[]

== Connector Reference

There are two sets of parameters that support source connectors.

=== Astra Streaming

include::pulsar-io:partial$connectors/sources/astra-config-params.adoc[]

[#configs]
=== Debezium MySQL (`configs`)

These parameters are set in the `configs` section of the connector configuration.

The {product} MySQL source connector supports all configuration properties provided in Debezium's connector. Please refer to https://debezium.io/documentation/reference/{debezium-version}/connectors/mysql.html#mysql-connector-properties[Debezium MySQL connector properties] for a complete list.

== What's next?

For a list of supported MySQL versions, see the https://debezium.io/releases/{debezium-version}/[Debezium documentation].

For a detailed explanation of Debezium's MySQL connector, see the https://debezium.io/documentation/reference/{debezium-version}/connectors/mysql.html[Debezium documentation].

For more examples, see the https://pulsar.apache.org/docs/io-debezium-source/#example-of-mysql[{pulsar} MySQL documentation].

