= Connectors
:attribute-missing: skip
:slug: astra-streaming-connectors
:page-tag: connectors,sources
:navtitle: Pulsar IO Connectors

:page-tag: astra-streaming,dev,develop,pulsar,go

{product_name} offers fully-managed Apache Pulsar™ connectors. 

Create, monitor, and manage source connectors through our simple UI, the `pulsar-admin` CLI, or RESTful API. Connect popular data sources to Apache Pulsar topics or sink data from Pulsar topics to popular systems.

{product_name} supports this list of Apache Pulsar sink connectors.  

[NOTE]
====
{product_name} does not support custom sink or source connectors.
====

== Source Connectors

[#source-connectors]
include::partial$connectors/sources/source-connectors.adoc[tag=production]

== Experimental Connectors

DataStax is always experimenting with connectors. Below are the connectors currently in development that have not yet been promoted to official support in *{product_name}*. 

To receive access to these connectors, send a request to {request_feature_access_email} and include your Astra account UUID.

=== Source Connectors (experimental)

[#source-experimental]
include::partial$connectors/sources/source-connectors.adoc[tag=source-experimental]

== Listing Source Connectors

To list available source connectors in your {product_name} tenant, use any of the following:

[tabs]
====
Pulsar Admin::
+
--
Assuming you have downloaded client.conf to the Pulsar folder:

[source,shell,subs="attributes+"]
----
./bin/pulsar-admin sources available-sources
----
--

cURL::
+
--

You'll need to create an Astra Streaming API token to use with the Rest API. This is different from your Astra tokens. 

Navigate to the *Settings* area in the Astra Streaming UI and choose *Create Token*.

Retrieve the web service URL from the *Connect* tab in the Astra Streaming UI.

[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

[source,shell,subs="attributes+"]
----
curl "$WEB_SERVICE_URL/admin/v3/sources/builtinsources" -H "Authorization: $ASTRA_STREAMING_TOKEN"
----
--
====

== What's next?

For more on Pulsar IO connectors, see the https://pulsar.apache.org/docs/en/io-overview/[Pulsar documentation^].
