include::pulsar-io:partial$connectors/function-params-tip.adoc[]

The following table lists the {product} {pulsar-short} source connector configuration properties by JSON field name.
For the equivalent command line arguments and more information about these properties, see the following:

* https://pulsar.apache.org/docs/3.1.x/functions-cli/[{pulsar-short} Functions CLI and YAML configuration reference]
* https://pulsar.apache.org/reference/#/{pulsar-version}.x/pulsar-admin/sources[`pulsar-admin sources` specification]

[cols=3]
|===
|Field name |Required |Description

|`archive`
|Yes
|The built-in {product} {pulsar-short} connector that you want to deploy.
Formatted as `builtin://**CONNECTOR**`, such as `builtin://debezium-mysql`.

|`batchBuilder`
|No
|The batch construction method: `DEFAULT` or `KEY_BASED`.

Default: `DEFAULT`

|`batchSourceConfig`
|No
|The batch source configuration key-value as a JSON string.

|`configs`
|No
|A JSON-formatted key-value map containing configuration properties specific to the connector type, such as provider-specific authentication and integration settings.
For available options, see <<configs>>.

Default: `{}` (Empty map, uses defaults)

|`customRuntimeOptions`
|No
|A string that encodes options to configure the https://pulsar.apache.org/docs/3.1.x/functions-concepts/#function-runtime[{pulsar} function runtime].

|`name`
|Yes
|The name for the connector.
It must start with a lowercase letter, and contain only numbers, hyphens (`-`), and lowercase letters.
{company} recommends a memorable, human-readable name that summarizes the connector's purpose.
For example: `{connectorType}-source-prod-us-east-1`.

|`namespace`
|Yes
|The namespace in your {pulsar-short} tenant where you want to create the connector.

|`parallelism`
|Yes
|The number of https://pulsar.apache.org/docs/3.1.x/functions-concepts/#function-instance[{pulsar-short} function instances] to run.

Default: `1`

|`processingGuarantees`
|Yes
|The messaging delivery semantic to use when writing to topics: `ATLEAST_ONCE`, `ATMOST_ONCE`, or `EFFECTIVELY_ONCE`.

Respect for the processing guarantee depends on the connector implementation.

For more information, see the {pulsar-short} documentation on https://pulsar.apache.org/docs/3.1.x/functions-concepts/#processing-guarantees-and-subscription-types[Function processing guarantees] and https://pulsar.apache.org/docs/3.1.x/io-overview/#processing-guarantee[Processing guarantees in I/O connectors].

Default: `ATLEAST_ONCE`

|`producerConfig`
|No
a|A JSON string containing a https://pulsar.apache.org/docs/3.1.x/functions-cli/#producerconfig[custom producer configuration].
By default, most values are `null` or empty.
For example:

[source,json]
----
  "producerConfig": {
    "maxPendingMessages": null,
    "maxPendingMessagesAcrossPartitions": null,
    "useThreadLocalProducers": false,
    "cryptoConfig": null,
    "batchBuilder": ""
  },
----

|`resources`
|No
|A JSON string describing the compute resources to allocate to each https://pulsar.apache.org/docs/3.1.x/functions-concepts/#function-instance[{pulsar-short} function instance].
For example: `{"cpu":0.25,"disk":1000000000,"ram":500000000}`.

|`runtimeFlags`
|No
|A string that encodes flags to pass to the https://pulsar.apache.org/docs/3.1.x/functions-concepts/#function-runtime[{pulsar} function runtime].
Only applicable to process and Kubernetes runtimes.

|`schemaType`
|No
|The schema type used to encode messages emitted from a {pulsar-short} source.
Accepts either a built-in schema like `avro` or `json`, or a custom `Schema` class name.

|`secrets`
|No
|If security is enabled on your https://pulsar.apache.org/docs/3.1.x/functions-concepts/#function-worker[function workers], you can provide a map of secret names (`secretName`) to secrets provider configuration objects.
The `secretName` is used by the connector to reference the secret.
The mapped object contains the required properties to fetch the secret from the secrets provider.

To get the types for the values in this mapping, use the `https://pulsar.apache.org/docs/3.1.x/functions-develop-security/[SecretProviderConfigurator.getSecretObjectType()]` method.

This is separate from the {pulsar-short} authentication token and security settings passed elsewhere in the connector configuration.

|`serdeClassName`
|No
|The SerDe classname for the source.

|`tenant`
|Yes
|The {pulsar-short} tenant where you want to create the connector.

|`topicName`
|Yes
|An existing topic in your {product} tenant where messages are published.
Must be formatted as a full persistent or non-persistent topic name, such as `persistent://$TENANT/$NAMESPACE/$TOPIC`.

|`typeClassName`
|Yes
|The class reference for the connector type.
Begins with `org.apache.pulsar`, such as `org.apache.pulsar.common.schema.KeyValue` or `org.apache.pulsar.io.debezium.mysql.DebeziumMysqlSource`.
|===