=== Info

[tabs]
====
Pulsar Admin::
+
--
Assuming you have downloaded client.conf to the Pulsar folder:

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/pulsar-admin-info.sh[]
----
--

cURL::
+
--

You'll need to create an Astra Streaming API token to be used with the REST API. This is different from your Astra tokens. 

Navigate to the "Settings" area in the Astra Streaming UI and choose "Create Token".

Retrieve the web service URL from the "Connect" tab in the Astra Streaming UI.

[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/curl-info.sh[]
----
--

Sample Config Data::
+
--
include::example$connectors/sources/{connectorType}/sample-data.adoc[]
--
====

=== Health

[tabs]
====
Pulsar Admin::
+
--
Assuming you have downloaded the client.conf to the pulsar folder.

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/pulsar-admin-status.sh[]
----
--

cURL::
+
--

You'll need to create an Astra Streaming API token to be used with the REST API. This is different from your Astra tokens. 

Navigate to the "Settings" area in the Astra Streaming UI and choose "Create Token".

Retrieve the web service URL from the "Connect" tab in the Astra Streaming UI.

[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/curl-status.sh[]
----
--

Response::
+
--
include::partial$connectors/sources/curl-status-response.adoc[]
--
====

=== Metrics

Astra Streaming exposes Prometheus formatted metrics for every connector. Refer to xref:astream-scrape-metrics.adoc[scrape metrics with Prometheus] page for more detail.