=== Info

[tabs]
====
{pulsar-short} Admin::
+
--
Assuming you have downloaded client.conf to the {pulsar-short} folder:

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/pulsar-admin-info.sh[]
----
--

cURL::
+
--
You need a {pulsar-short} token for REST API authentication.
This is different from your {astra-db} application tokens.

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click your tenant's name, and then click the *Settings* tab.

. Click *Create Token*.

. Copy the token, store it securely, and then click *Close*.

. Click the *Connect* tab, and then copy the *Web Service URL*.

. Create environment variables for your tenant's token and web service URL:
+
[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

. Use these values to form curl commands to the REST API:
+
[source,shell,subs="attributes+"]
----
include::example$connectors/sources/curl-info.sh[]
----
--

Sample Config Data::
+
--
include::example$connectors/sources/{connectorType}/sample-data.adoc[]
--
====

=== Health

[tabs]
====
{pulsar-short} Admin::
+
--
Assuming you have downloaded the client.conf to the pulsar folder.

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/pulsar-admin-status.sh[]
----
--

cURL::
+
--
You need a {pulsar-short} token for REST API authentication.
This is different from your {astra-db} application tokens.

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click your tenant's name, and then click the *Settings* tab.

. Click *Create Token*.

. Copy the token, store it securely, and then click *Close*.

. Click the *Connect* tab, and then copy the *Web Service URL*.

. Create environment variables for your tenant's token and web service URL:
+
[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

. Use these values to form curl commands to the REST API:
+
[source,shell,subs="attributes+"]
----
include::example$connectors/sources/curl-status.sh[]
----
--
+
Response::
+
--
include::partial$connectors/sources/curl-status-response.adoc[]
--
====

=== Metrics

{product} exposes Prometheus formatted metrics for every connector. Refer to xref:astra-streaming:operations:astream-scrape-metrics.adoc[scrape metrics with Prometheus] page for more detail.