=== Info

[tabs]
====
{pulsar-short} Admin::
+
--
Assuming you have downloaded client.conf to the {pulsar-short} folder:

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/pulsar-admin-info.sh[]
----
--

cURL::
+
--

You'll need to create an {product} API token to be used with the REST API. This is different from your Astra tokens. 

Navigate to the "Settings" area in the {product} UI and choose "Create Token".

Retrieve the web service URL from the "Connect" tab in the {product} UI.

[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/curl-info.sh[]
----
--

Sample Config Data::
+
--
include::example$connectors/sources/{connectorType}/sample-data.adoc[]
--
====

=== Health

[tabs]
====
{pulsar-short} Admin::
+
--
Assuming you have downloaded the client.conf to the pulsar folder.

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/pulsar-admin-status.sh[]
----
--

cURL::
+
--

You'll need to create an {product} API token to be used with the REST API. This is different from your Astra tokens. 

Navigate to the "Settings" area in the {product} UI and choose "Create Token".

Retrieve the web service URL from the "Connect" tab in the {product} UI.

[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

[source,shell,subs="attributes+"]
----
include::example$connectors/sources/curl-status.sh[]
----
--

Response::
+
--
include::partial$connectors/sources/curl-status-response.adoc[]
--
====

=== Metrics

{product} exposes Prometheus formatted metrics for every connector. Refer to xref:astra-streaming:operations:astream-scrape-metrics.adoc[scrape metrics with Prometheus] page for more detail.