== Edit the connector

To update a connector, pass the new configuration definition to the connector.
For example, if you created the connector with a configuration file, you can pass an updated configuration file.

You can include the entire configuration or only the parameters that you want to change.
Additionally, some parameters can be modified with specific arguments, such as `--parallelism`.

To get the current configuration, see xref:pulsar-io:connectors/index.adoc#get-sink-connector-configuration-data[Get sink connector configuration data].

.pulsar-admin CLI
[source,shell,subs="+attributes"]
----
include::partial$connectors/sinks/cli-update.sh[]
----

.{pulsar-short} Admin API
[source,shell,subs="+attributes"]
----
include::partial$connectors/sinks/curl-update.sh[]
----

== Manage the connector

* xref:pulsar-io:connectors/index.adoc#start-a-sink-connector[Start a sink connector]
* xref:pulsar-io:connectors/index.adoc#stop-a-sink-connector[Stop a sink connector]
* xref:pulsar-io:connectors/index.adoc#restart-a-sink-connector[Restart a sink connector]
* xref:pulsar-io:connectors/index.adoc#get-sink-connector-status[Get sink connector status]
* xref:pulsar-io:connectors/index.adoc#delete-a-sink-connector[Delete a sink connector]