== Start or stop the connector

See the following:

* xref:pulsar-io:connectors/index.adoc#start-a-sink-connector[Start a sink connector]
* xref:pulsar-io:connectors/index.adoc#stop-a-sink-connector[Stop a sink connector]
* xref:pulsar-io:connectors/index.adoc#restart-a-sink-connector[Restart a sink connector]

== Check connector status

See xref:pulsar-io:connectors/index.adoc#get-sink-connector-status[Get sink connector status].

== Edit the connector

To update a connector, pass the new configuration definition to the connector.
You can include the entire configuration or only the parameters that you want to change.

With the {pulsar-short} Admin CLI, you can use `sink-config`, or use specific command line arguments to modify individual configuration parameters.

To get the current configuration, see xref:pulsar-io:connectors/index.adoc#get-sink-connector-configuration-data[Get sink connector configuration data].

.{pulsar-short} Admin CLI
[source,shell,subs="+attributes"]
----
include::example$connectors/sinks/{connectorType}/pulsar-admin-update.sh[]
----

.{pulsar-short} Admin API
[source,shell,subs="+attributes"]
----
include::partial$connectors/sinks/curl-update.sh[]
----

== Delete the connector

See xref:pulsar-io:connectors/index.adoc#delete-a-sink-connector[Delete a sink connector].