= Connectors
:navtitle: Connector Overview
:page-tag: connectors,sinks,sources,astra-streaming,dev,develop,pulsar,go

{product} offers fully-managed {pulsar-reg} connectors.

Create, monitor, and manage both source and sink connectors through our simple UI, the `pulsar-admin` CLI, or RESTful API.
Connect popular data sources to {pulsar} topics or sink data from {pulsar-short} topics to popular systems.

Below is a list of {pulsar} source and sink connectors supported by {product}.

[NOTE]
====
{product} does not support custom sink or source connectors.
====

== Sink Connectors

[#sink-connectors]
include::partial$connectors/sinks/sink-connectors.adoc[tag=production]

== Source Connectors

[#source-connectors]
include::partial$connectors/sources/source-connectors.adoc[tag=production]

== Experimental Connectors

{company} is always experimenting with connectors. Below are the connectors currently in development that have not yet been promoted to official support in *{product}*.

To get access to these connectors, contact {support-url}[{company} Support].

=== Sink Connectors (experimental)

[#sink-experimental]
include::partial$connectors/sinks/sink-connectors.adoc[tag=sink-experimental]

=== Source Connectors (experimental)

[#source-experimental]
include::partial$connectors/sources/source-connectors.adoc[tag=source-experimental]

== Listing Sink Connectors

To list available sink connectors in your {product} tenant, use any of the following.

[tabs]
====
{pulsar-short} Admin::
+
--
include::partial$connectors/sinks/pulsar-admin-tab-prereq.adoc[]

[source,shell,subs="attributes+"]
----
./bin/pulsar-admin sinks available-sinks
----
--

curl::
+
--
// tag::rest-env-vars[]
You need a {pulsar-short} token for REST API authentication.
This is different from your {astra-db} application tokens.

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click your tenant's name, and then click the *Settings* tab.

. Click *Create Token*.

. Copy the token, store it securely, and then click *Close*.

. Click the *Connect* tab, and then copy the *Web Service URL*.

. Create environment variables for your tenant's token and web service URL:
+
[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----
// end::rest-env-vars[]

. Use these values to form curl commands to the REST API:
+
[source,shell,subs="attributes+"]
----
curl "$WEB_SERVICE_URL/admin/v3/sinks/builtinsinks" -H "Authorization: $ASTRA_STREAMING_TOKEN"
----
--
====

== Listing Source Connectors

To list available source connectors in your {product} tenant, use any of the following.

[tabs]
====
{pulsar-short} Admin::
+
--
include::partial$connectors/sources/pulsar-admin-tab-prereq.adoc[]

[source,shell,subs="attributes+"]
----
./bin/pulsar-admin sources available-sources
----
--

cURL::
+
--
include::pulsar-io:connectors/index.adoc[tag=rest-env-vars]

[source,shell,subs="attributes+"]
----
curl "$WEB_SERVICE_URL/admin/v3/sources/builtinsources" -H "Authorization: $ASTRA_STREAMING_TOKEN"
----
--
====

== What's next?

For more on {pulsar-short} IO connectors, see the https://pulsar.apache.org/docs/en/io-overview/[{pulsar-short} documentation].