= {astra-db} (cassandra-enhanced)
:connectorType: cassandra-enhanced

The {astra-db} sink connector reads messages from {pulsar} topics and writes them to {astra-db} databases.

{company} {astra-db} sink connector is based on the open-source xref:pulsar-connector:ROOT:index.adoc[{cass} sink connector for {pulsar-reg}].
Depending on how you deploy the connector, it can be used to sink topic messages with a table in {astra-db} or a table in a self-managed {cass-short} cluster.
For the complete connector code, see the https://github.com/datastax/pulsar-sink[{company} {pulsar-short} sink connector GitHub repository].

You can configure this connector with the {astra-ui}, the `pulsar-admin` CLI, or the {pulsar-short} Admin API.
The {astra-ui} provides the most simplified and guided configuration, and it is only suitable for connecting to {astra-db} databases.
With the CLI and API, you must provide the complete configuration programmatically, but you can use these tools to connect to either {astra-db} databases or self-managed {cass-short} clusters.
A {pulsar-short} token is required for all configuration methods.

This reference assumes you are connecting to a {cass-short} table using the {pulsar-short} Admin API or CLI.

== Create the connector

include::partial$connectors/sinks/get-started.adoc[]

include::partial$connectors/sinks/manage.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== {pulsar-short} sink connector parameters

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== {cass-short} Connection (`configs`)

These values are provided in the `Configs` area:

[cols=4]
|===
| Name | Required | Default | Description

| auth
| yes
| `{}`
| Refer to the auth properties reference

| cloud.secureConnectBundle
| yes
|
|Can either be a path to your database's Secure Connect Bundle (SCB) zip or a base64 encoding of the zip provided it in the format `base64:<b64 string>`.

| compression
| yes
| None
|

| connectionPoolLocalSize
| yes
| 4
|

| ignoreErrors
| yes
| None
|

| jmx
| yes
| true
|

| maxConcurrentRequests
| yes
| 500
|

| maxNumberOfRecordsInBatch
| yes
| 32
|

| queryExecutionTimeout
| yes
| 30
|

| task.max
| yes
| 1
|

| tasks.max
| yes
| 1
|

| topic
| yes
| `{}`
| Refer to the topic properties reference

| topics
| yes
|
|The topic name to watch
|===

=== Auth Properties

These values are provided in the `auth` area of the preceding {cass-short} connection parameters:

[cols=3]
|===
| Name | Required | Default

| gssapi
| yes
| `{ "service": "dse" }`

| password
| yes
|

| provider
| yes
| None

| username
| yes
| `token`
|===

=== Topic Properties

These values are provided in the `topic` area of the preceding {cass-short} connection parameters.

Refer to the official documentation for a xref:pulsar-connector:ROOT:cfgRefPulsarDseConnection.adoc[connection properties reference].

=== Mapping topic data to table columns

An essential part of using this sink connector is mapping message values to table columns.
There are many factors that influence how this done and what is possible.

While the preceding examples showed how to configure the connector in one large command, it is easier to manage this as a separate file.
The following steps explain how to configure the connector using a JSON configuration file with the minimum required values.

For a more detailed example of this pattern, see the xref:pulsar-connector:ROOT:pulsarQuickStart.adoc[{pulsar-short} Connector single instance quickstart].

. Create a file named `configs.json` with the following content:
+
[source,json,subs="+quotes"]
----
"archive": "builtin://cassandra-enhanced",
"tenant": "${TENANT}",
"namespace": "${NAMESPACE}",
"name": "${SINK_NAME}",
"inputs": ["${TOPIC}"],
"configs": {
  "topics": "${TOPIC}",
  "cloud.secureConnectBundle": "**SCB**",
  "topic": {
   "${TOPIC}": {
      "**KEYSPACE_NAME**": {
        "**TABLE_NAME**": {
          **CONNECTION_PROPERTIES**,
          "mapping": "**MAPPING_STRING**"
        }
      }
    }
  }
}
----
+
Replace the following:
+
* **SCB**: The path to your database's Secure Connect Bundle (SCB) zip or a base64 encoding of the SCB zip.
* **KEYSPACE_NAME**: The name of the keyspace in your database that contains the table you want to connect to a topic.
* **TABLE_NAME**: The name of the table to connect to a topic.
* **TABLE_CONNECTION_PROPERTIES**: Additional topic-to-table connection properties, if required.
For more information, see xref:pulsar-connector:ROOT:cfgRefPulsarDseTable.adoc[].
* **MAPPING_STRING**: The mapping string for the table columns as a comma-separated list of column names and message value fields.
For example:
+
[source,text]
----
symbol=value.symbol, ts=value.ts, exchange=value.exchange, industry=value.industry, name=key, value=value.value
----
+
For more mapping examples, see xref:pulsar-connector:ROOT:cfgPulsarMapTopicTable.adoc[Mapping pulsar topics to database tables].

. Use the `pulsar-admin` CLI to create the connector with your JSON file:
+
[source,shell]
----
./bin/pulsar-admin sinks create \
	--name ${SINK_NAME} \
	--classname com.datastax.oss.sink.pulsar.StringCassandraSinkTask \
	--sink-config-file configs.json \
	--sink-type cassandra-enhanced
----