= {astra-db} and {cass}
:connectorType: cassandra-enhanced

The open-source https://pulsar.apache.org/docs/3.1.x/io-cassandra-sink/[{pulsar-reg} {cass-short} sink connector] (`cassandra`) reads messages from {pulsar} topics and writes them to {cass} databases.

The xref:pulsar-connector:ROOT:index.adoc[{company} {pulsar} sink connector] (`{connectorType}`) extends the open-source connector by adding support for {company} product connections.
This includes {astra-db} connections with a Secure Connect Bundle (SCB) and {astra} application token.

This means that you can use this sink connector to write messages to tables in {astra-db} or self-managed {cass-short} clusters.

//Astra Streaming only
You can configure this connector with the {astra-ui}, the `pulsar-admin` CLI, or the {pulsar-short} Admin API.
The {astra-ui} provides a guided configuration process, but it is only suitable for connecting to {astra-db} databases.
With the CLI and API, you can connect to {astra-db} or a self-managed {cass-short} cluster.

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

[TIP]
====
The preceding example connects to a self-managed {cass-short} cluster.

For an {astra-db} example, see <<topic>>.

For all connection parameters, see <<configs>>.
====

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} sink connector parameters

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== {company} {pulsar} sink connector parameters (`configs`)

These parameters are set in the `configs` section.

The relevant and required parameters depend on whether you are connecting to {astra-db} or a self-managed {cass-short} cluster, as well as the cluster configuration.

[TIP]
====
The following table includes commonly used parameters.
For all parameters and more information, see the xref:pulsar-connector:ROOT:index.adoc[{company} {pulsar} sink connector documentation].
====

[cols=4]
|===
| Name | Required | Default | Description

|`auth`
|Yes
|`{}`
|Contains the xref:pulsar-connector:ROOT:cfgRefPulsarDseConnection.adoc#authentication-parameters[authentication parameters] to connect to the database.

|`cloud.secureConnectBundle`
|Yes for {astra-db}
|`null`
|The path to your {astra-db} database's SCB zip file, or a base64 encoding of the SCB zip file (`base64:**ENCODED_STRING**`).

Only use this parameter for {astra-db} connections.

For self-managed clusters, use `ssl`.

|`compression`
|yes
|`None`
|The compression algorithm to use.

|`connectionPoolLocalSize`
|Yes
|4
|Number of connections to each node in the local datacenter.

|`contactPoints`
|Yes for self-managed clusters
|`[localhost]`
|Either `[localhost]` or a comma-separated list of hostnames or IP addresses for your self-managed {cass-short} cluster nodes.

If `contactPoints` is set to a list of hosts, then `loadBalancing.localDc` is required.

If `cloud.secureConnectBundle` is set, then `contactPoints` is ignored.
The contact points are set by the SCB.

|`ignoreErrors`
|Yes
|`None`
|Sets the xref:pulsar-connector:ROOT:cfgPulsarConfigureErrorHandling.adoc[error handling behavior].

|`jmx`
|Yes
|`true`
|Whether to collect and report metrics using Java Management Extensions (JMX).

|`maxConcurrentRequests`
|Yes
|`500`
|The maximum number of concurrent requests that can be sent to each connected node.

|`maxNumberOfRecordsInBatch`
|Yes
|`32`
|The maximum number of records to include in a batch write to the database.

|`queryExecutionTimeout`
|Yes
|`30`
|CQL statement execution timeout limit in seconds.

|`ssl`
|Depends on cluster configuration
|`{}`
|Contains xref:pulsar-connector:ROOT:cfgRefPulsarDSEConnection.adoc[SSL-encryption parameters] for self-managed clusters with client-to-node encryption enabled.

For {astra-db}, use `cloud.secureConnectBundle`, which includes the SSL encryption configuration.
If `cloud.secureConnectBundle` is set, then `ssl` is ignored.

|`topic`
|Yes
|`{}`
|Contains the <<topic,topic-to-table mapping parameters>>.

|`topics`
|Yes
|`[]`
|The names of topics to subscribe to.

For each topic in `topics`, there must be a corresponding entry in the `topic` section.
|===

[#topic]
=== Topic-to-table mapping parameters (`topic`)

The `topic` section of the `<<configs,configs>>` contains xref:pulsar-connector:ROOT:cfgRefPulsarDseTable.adoc[topic-to-table mapping parameters].

The mapping determines which table receives messages from a {pulsar-short} topic, and how the message `value` fields are written to the table columns.

There are many mapping parameters and values to support different write options, value translations, and data formats.

The following example shows a simplified `configs` object that maps one topic to a table in an {astra-db} database:

[source,json]
----
"configs": {
  "auth": {
    "username": "token",
    "password": "${ASTRA_APPLICATION_TOKEN}"
  },
  "cloud.secureConnectBundle": "path/to/scb.zip",
  "topics": "${TOPIC}",
  // ...
  // Other configs parameters
  // ...
  "topic": {
   "${TOPIC}": {
      "${KEYSPACE_NAME}": {
        "${TABLE_NAME}": {
          "mapping": "column1=value.fieldA,column2=value.fieldC,column3=value.fieldG,column8=value.fieldW"
          // ...
          // Other mapping parameters, such as codec and nullToUnset
          // ...
        }
      }
    }
  }
}
----

The `mapping` string is a comma-separated list of table column names and message `value` fields.

If your connector subscribes to multiple topics, create an entry for each topic in the `topic` section.

For a more information and examples, see the xref:pulsar-connector:ROOT:index.adoc[{company} {pulsar} sink connector documentation].

== See also

* https://github.com/datastax/pulsar-sink[{company} {pulsar} connector GitHub repository]