= {astra-db} ({cass-reg} enhanced)
:connectorName: astra-db-sink
:connectorType: astra-db

{company} {astra-db} Sink Connector is based on the open-source xref:pulsar-connector:ROOT:index.adoc[{cass-reg} sink connector for {pulsar-reg}]. Depending on how you deploy the connector, it can be used to sink topic messages with a table in {astra-db} or a table in a {cass-short} cluster outside of DB.

The {product} portal provides simple way to connect this sink and a table in {astra-db} with simply a token. Using `pulsar-admin` or the REST API, you can configure the sink to connect with a {cass-short} connection manually.

This reference assumes you are manually connecting to a {cass-short} table.

[TIP]
====
If you would like to see the code, refer to the https://github.com/datastax/pulsar-sink[open source here].
====

== Get Started

include::partial$connectors/sinks/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sinks/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sinks/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== {pulsar-short} sink connector parameters

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sinks/astra.csv[]
|===

=== {cass-short} Connection

These values are provided in the `Configs` area:

[cols=4]
|===
| Name | Required | Default | Description

| auth
| yes
| `{}`
| Refer to the auth properties reference

| cloud.secureConnectBundle
| yes
|
|Can either be a path to your database's Secure Connect Bundle (SCB) zip or a base64 encoding of the zip provided it in the format `base64:<b64 string>`.

| compression
| yes
| None
|

| connectionPoolLocalSize
| yes
| 4
|

| ignoreErrors
| yes
| None
|

| jmx
| yes
| true
|

| maxConcurrentRequests
| yes
| 500
|

| maxNumberOfRecordsInBatch
| yes
| 32
|

| queryExecutionTimeout
| yes
| 30
|

| task.max
| yes
| 1
|

| tasks.max
| yes
| 1
|

| topic
| yes
| `{}`
| Refer to the topic properties reference

| topics
| yes
|
|The topic name to watch
|===

=== Auth Properties

These values are provided in the `auth` area of the preceding {cass-short} connection parameters:

[cols=3]
|===
| Name | Required | Default

| gssapi
| yes
| `{ "service": "dse" }`

| password
| yes
|

| provider
| yes
| None

| username
| yes
| `token`
|===

=== Topic Properties

These values are provided in the `topic` area of the preceding {cass-short} connection parameters.

Refer to the official documentation for a xref:pulsar-connector:ROOT:cfgRefPulsarDseConnection.adoc[connection properties reference].

=== Mapping topic data to table columns

An essential part of using this sink connector is mapping message values to table columns.
There are many factors that influence how this done and what is possible.

While the preceding examples showed how to configure the connector in one large command, it is easier to manage this as a separate file.
The following steps explain how to configure the connector using a JSON configuration file with the minimum required values.

For a more detailed example of this pattern, see the xref:pulsar-connector:ROOT:pulsarQuickStart.adoc[{pulsar-short} Connector single instance quickstart].

. Create a file named `configs.json` with the following content:
+
[source,json,subs="+quotes"]
----
"archive": "builtin://cassandra-enhanced",
"tenant": "**TENANT_NAME**",
"namespace": "**NAMESPACE_NAME**",
"name": "**CONNECTOR_NAME**",
"inputs": ["**TOPIC_NAME**"],
"configs": {
  "topics": "**TOPIC_NAME**",
  "cloud.secureConnectBundle": "**SCB**",
  "topic": {
   "**TOPIC_NAME**": {
      "**KEYSPACE_NAME**": {
        "**TABLE_NAME**": {
          **CONNECTION_PROPERTIES**,
          "mapping": "**MAPPING_STRING**"
        }
      }
    }
  }
}
----
+
Replace the following:

* **TENANT_NAME**: Your tenant's name.
* **NAMESPACE_NAME**: The tenant's associated namespace name.
* **CONNECTOR_NAME**: The name of the connector.
* **TOPIC_NAME**: In `inputs` and `configs.topics`, specify the names of the topics to connect.
Specify topic names only; don't use the full topic addresses.
You can specify multiple topics.
Define one `configs.topic` object for each topic that you want to connect.
* **SCB**: The path to your database's Secure Connect Bundle (SCB) zip or a base64 encoding of the SCB zip.
* **KEYSPACE_NAME**: The name of the keyspace in your database that contains the table you want to connect to a topic.
* **TABLE_NAME**: The name of the table to connect to a topic.
* **TABLE_CONNECTION_PROPERTIES**: Additional topic-to-table connection properties, if required.
For more information, see xref:pulsar-connector:ROOT:cfgRefPulsarDseTable.adoc[].
* **MAPPING_STRING**: The mapping string for the table columns as a comma-separated list of column names and message value fields.
For example:
+
[source,text]
----
symbol=value.symbol, ts=value.ts, exchange=value.exchange, industry=value.industry, name=key, value=value.value
----
+
For more mapping examples, see xref:pulsar-connector:ROOT:cfgPulsarMapTopicTable.adoc[Mapping pulsar topics to database tables].

. Use the `pulsar-admin` CLI to create the connector with your JSON file:

[source,shell]
----
./bin/pulsar-admin sinks create \
	--name dse-sink-kv \
	--classname com.datastax.oss.sink.pulsar.StringCassandraSinkTask \
	--sink-config-file configs.json \
	--sink-type cassandra-enhanced
----