= Cloud Storage
:connectorType: cloud-storage

The Cloud Storage sink connector reads messages from {pulsar-short} topics and writes them to cloud storage using specified format, such as Avro or Parquet.

The following cloud storage providers are supported:

* https://aws.amazon.com/s3/[AWS S3]
* https://cloud.google.com/storage[Google Cloud Storage]
* https://azure.microsoft.com/en-us/products/storage/blobs[Microsoft Azure Blob Storage]

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

[#pulsar-sink-connector-properties]
=== {pulsar-short} sink connector properties

include::pulsar-io:partial$connectors/sinks/pulsar-config-params.adoc[]

[#configs]
== Cloud Storage sink connector properties (`configs`)

In the `configs` section of the connector configuration, set the following data transformation and cloud storage connection properties.

[cols=4]
|===
|Name |Required |Default |Description

|`azureStorageAccountConnectionString`
|Yes for Azure

Not used for GCS or AWS
|Empty
|The Azure Blob Storage connection string to authenticate with the storage account.

If not set, you must set either `azureStorageAccountSASToken` _or_ both `azureStorageAccountKey` and `azureStorageAccountName`.

|`azureStorageAccountKey` and `azureStorageAccountName`
|Yes for Azure

Not used for GCS or AWS
|Empty
|The Azure Blob Storage account key and account name to authenticate with the storage account.
You must provide both properties when using this authentication method.

If not set, you must set either `azureStorageAccountSASToken` _or_ `azureStorageAccountConnectionString`.

|`azureStorageAccountSASToken`
|Yes for Azure

Not used for GCS or AWS
|Empty
|The Azure Blob Storage account SAS token to authenticate with the storage account.

If not set, you must set either `azureStorageAccountConnectionString` _or_ both `azureStorageAccountKey` and `azureStorageAccountName`.

|`avroCodec`
|No
|`snappy`
|If `formatType` is `avro`, set the codec compression type: `bzip2`, `deflate`, `snappy`, `xz`, `zstandard`, or `null` (no compression).

|`batchSize`
|No
|`10`
|The number of records submitted in a batch.

By default, `batchSize` and `pendingQueueSize` are equal.

|`batchTimeMs`
|No
|`1000`
|The interval for batch submission.

|`bucket`
|Yes
|`null`
|The name of the cloud storage bucket or container to write to.

|`bytesFormatTypeSeparator`
|No
|`0x10`
|This separator is inserted between records for the `formatType` of bytes.
An input record that contains the line separator will look like multiple records in the output object.

|`endpoint`
|Yes for AWS and Azure

Not used for GCS
|`null`
|The endpoint for your AWS S3 or Azure Blob Storage service.

|`formatType`
|Yes
|`json`
|The desired format type for the output to cloud storage: `json`, `avro`, `bytes`, or `parquet`.

For supported schema conversions and limitations, see <<data-format-types>>.

See also `avroCodec`, `bytesFormatTypeSeparator`, `jsonAllowNaN`, `parquetCodec`, and `withMetadata`.

|`gcsServiceAccountKeyFileContent`
|Yes for GCS

Not used for AWS or Azure
|Empty
|The contents of a JSON GCS service account key file.
If empty or not set, the connector attempts to read credentials from `gcsServiceAccountKeyFilePath`.

|`gcsServiceAccountKeyFilePath`
|Yes for GCS

Not used for AWS or Azure
|Empty
|The path to a JSON GCS service account key file.
If empty or not set, the connector attempts to read credentials from the system's `GOOGLE_APPLICATION_CREDENTIALS` environment variable.

|`jsonAllowNaN`
|No
|`false`
|If `formatType` is `json`, set this property to `true` if you want the connector to treat 'NaN', 'INF', '-INF' as valid floating number values.

This is disabled (`false`) by default because these values aren't compliant with the JSON specification.

|`maxBatchBytes`
|No
|`10000000`
|The maximum number of bytes in a batch.

|`parquetCodec`
|No
|`gzip`
|If `formatType` is `parquet`, set the codec compression type: `brotli`, `gzip`, `lzo`, `lz4`, `snappy`, `zstd`, or `null` (no compression).

|`partitionerType`
|No
|`partition`
a|The partitioning type:

* **`partition` (default)**: Partitions are based on topic partitions.
* **`time`**: Partitions are based on message publish time.
If using time-based partitioning, you can also set `timePartitionDuration` and `timePartitionPattern`.

|`partitionerUseIndexAsOffset`
|No
|`false`
|Whether to use the the {pulsar-short} message index as the offset (message UUID) instead of the record sequence.

* **`false` (default)**: Use the record sequence as the offset.

* **`true`**: Use the message index as the offset, if available.
This is recommended when using batching.

If the broker doesn't expose index metadata, or the record doesn't have index metadata, then the sequence is used.

|`pathPrefix`
|No
|`null`
|If empty or not set, the output files are stored at the root of the specified `bucket`.

If set, output files are stored in a folder at the path within the bucket.
Format the path as `**DIRECTORY**/**SUBDIRECTORY**/` with a trailing slash but no leading slash.

|`pendingQueueSize`
|No
|`10`
|The number of records buffered in queue.

By default, `batchSize` and `pendingQueueSize` are equal.

|`provider`
|Yes
|`null`
a|Specify the provider type for your cloud storage service:

* **Azure**: Only supports `azure-blob-storage`.
* **AWS S3**: Supports `aws-s3` or `s3v2`.
`s3v2` uses the AWS client, not the JCloud client.
* **GCS**: Only supports `google-cloud-storage`.

|`role` and `roleSessionName`
|Yes for AWS if using IAM roles

Not used for GCS or Azure
|`null`
|If using https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html[AWS IAM roles] for authentication to AWS S3, then set `role` to the IAM role name, and set `roleSessionName` to the IAM role instance identifier.
You must also set `secretAccessKey` and `accessKeyId`.

|`secretAccessKey` and `accessKeyId`
|Yes for AWS

Not used for GCS or Azure
|`null`
a|An AWS secret access key and access key ID that grant access to the specified `bucket`.
If using AWS IAM roles, you must also set `role` and `roleSessionName`.

Permission to write objects to the specified `bucket` are required.
The following https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-policy-language-overview.html[policies] are recommended:

- `s3:AbortMultipartUpload`
- `s3:GetObject*`
- `s3:PutObject*`
- `s3:List*`
- `s3:GetBucketLocation` (only if `endpoint` doesn't include the region)

|`skipFailedMessages`
|No
|`false`
a|Whether to skip messages that the connector fails to process for any reason, such as unsupported schema types:

* **`true`**: The connector skips failed messages by acknowledging them as though they were successfully processed.
* **`false` (default)**: The connector fails the message, and the message remains unacknowledged.

[TIP]
====
If you want the connector to send failed messages to a dead-letter topic, set `skipFailedMessages` to `false`, and set `maxMessageRetries` and `deadLetterTopic` in the <<pulsar-sink-connector-properties>>.
====

|`sliceTopicPartitionPath`
|No
|`false`
a|Whether to expand partitioned topic names into multiple directories in the bucket:

* **`true`**: Split the partitioned topic name into multiple directories in the bucket.
For example, `demo-partition-0` expands to `demo/partition-0/`.
* **`false` (default)**: Use the partitioned topic name as one directory name in the bucket path, such as `demo-partition-0/`.

See also `withTopicPartitionNumber`.

|`timePartitionDuration`
|No
|`86400000` (24 hours)
|If `partitionerType` is `time`, set the time interval for each partition.
Accepts either a string (`30d`, `24h`, or `30m`) or a number of milliseconds (`86400000`).

|`timePartitionPattern`
|No
|`yyyy-MM-dd`
|If `partitionerType` is `time`, set the datetime format using Java date and time format.

|`useHumanReadableMessageId`
|No
|`false`
a|Whether to use a human-readable string for `messageId` in message metadata:

* **`true`**: The `messageId` is a plain, human-readable string, such as `ledgerId:entryId:partitionIndex:batchIndex`.
* **`false` (default)**: The `messageId` is a Hex-encoded string.

|`useHumanReadableSchemaVersion`
|No
|`false`
a|Whether to use a human-readable string for the schema version in message metadata:

* **`true`**: The schema version is a plain, human-readable string.
* **`false` (default)**: The schema version is a Hex-encoded string.

|`withMetadata`
|No
|`false`
a|Whether to save message attributes as additional message metadata.

Ignored if `formatType` is `bytes`.

For example, when writing to Parquet (`formatType: "parquet"`) from the ProtobufNative schema, the connector writes messages with the `DynamicMessage` format.
If `withMetadata` is true, then the connector adds `+__message_metadata__+` to the messages with `PulsarIOCSCProtobufMessageMetadata`.

Therefore, given the following message:

[source,protobuf]
----
syntax = "proto3";
message User {
 string name = 1;
 int32 age = 2;
}
----

The connector writes the following output with metadata:

[source,parquet]
----
syntax = "proto3";
message PulsarIOCSCProtobufMessageMetadata {
 map<string, string> properties = 1;
 string schema_version = 2;
 string message_id = 3;
}
message User {
 string name = 1;
 int32 age = 2;
 PulsarIOCSCProtobufMessageMetadata __message_metadata__ = 3;
}
----

|`withTopicPartitionNumber`
|No
|`true`
|Whether to include the topic partition number in the object path:

* **`true` (default)**: Include the partition number in the object path, such as `topic-name/partition-0/`.
* **`false`**: Do not include the partition number in the object path, such as `topic-name/`.
This can be used to collapse partitions.

See also `sliceTopicPartitionPath`.
|===

[#data-format-types]
== Data format types

The `formatType` parameter supports JSON, Avro, Bytes, and Parquet formats.

The following table lists the supported conversions from {pulsar-short} schema types to each writer format, as well as any limitations or comments.

[cols=6]
|===
|{pulsar-short} Schema |Writer: Avro |Writer: JSON |Writer: Parquet |Writer: Bytes |Notes

|Primitive
|Not supported
|Supported
|Not supported
|Supported
|The JSON writer attempts to convert data with a `String` or `Bytes` schema to valid JSON, if possible.

|Avro
|Supported
|Supported
|Supported
|Supported
|

|JSON
|Supported
|Supported
|Supported
|Supported
|

|Protobuf
|Supported
|Supported
|Supported
|Supported
|The Protobuf schema is based on the Avro schema.
It uses Avro as an intermediate format, so it might not provide the best possible conversion.

|ProtobufNative
|Supported
|Not supported
|Supported
|Supported
|The ProtobufNative schema holds the Protobuf descriptor and the message.

When writing to Avro format, the connector uses `avro-protobuf` to do the conversion.

For information about Protobuf to Parquet, see `withMetadata` in <<configs>>.
|===