= Elasticsearch
:connectorType: elastic_search

Elasticsearch is the distributed, RESTful search and analytics engine at the heart of the Elastic Stack.
You can use Elasticsearch to store, search, and manage data for logs, metrics, search backend, application monitoring, and endpoint security.

The Elasticsearch sink connector reads messages from {pulsar} topics and writes them to https://www.elastic.co/elasticsearch/[Elasticsearch].

{product} currently supports {pulsar-reg} {pulsar-version}, which uses the https://opensearch.org/docs/1.2/clients/java-rest-high-level/[OpenSearch 1.2.4 library] to interact with
Elasticsearch.

To understand compatibility between OpenSearch and Elasticsearch, see https://opensearch.org/faq/#q1.8[question 1.8 in the OpenSearch FAQ].

For information about the OSS {pulsar} Elasticsearch sink connector, see the https://pulsar.apache.org/docs/io-elasticsearch-sink/[{pulsar-short} documentation].

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} sink connector parameters

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== Elasticsearch sink connector parameters (`configs`)

The {product} Elasticsearch sink connector supports all https://pulsar.apache.org/docs/io-elasticsearch-sink/#property[Elasticsearch sink connector properties] provided in the OSS {pulsar} Elasticsearch sink connector.

Set these parameters in the `configs` section of the connector configuration.