= Elasticsearch
:connectorType: elastic_search

The Elasticsearch sink connector reads messages from {pulsar-short} topics and writes them to https://www.elastic.co/elasticsearch/[Elasticsearch].

[#compatibility]
== Compatibility

{product} supports {pulsar-reg} {pulsar-version}, which uses the https://opensearch.org/docs/1.2/clients/java-rest-high-level/[OpenSearch 1.2.4 library].

For information about compatibility between OpenSearch and Elasticsearch, see the https://opensearch.org/faq[OpenSearch FAQ].

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} sink connector properties

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== Elasticsearch sink connector properties (`configs`)

Set these properties in the `configs` section of the connector configuration.

Generally, all properties provided in the https://pulsar.apache.org/docs/io-elasticsearch-sink[OSS {pulsar} Elasticsearch sink connector] are supported.
Exceptions include properties that aren't relevant to {product} and properties that are only present in <<compatibility,incompatible versions>>.