= Google BigQuery
:connectorType: bigquery

The {pulsar-short} BigQuery sink connector reads messages from {pulsar-short} topics and writes them to https://cloud.google.com/bigquery[Google BigQuery].

This connector doesn't integrate directly with BigQuery.
Instead, it uses the https://pulsar.apache.org/docs/adaptors-kafka/[{pulsar} Kafka Connect adaptor] to transform {pulsar-short} message data into a Kafka-compatible format, and then it uses the https://docs.confluent.io/kafka-connectors/bigquery/current/kafka_connect_bigquery_config.html[Kafka Connect BigQuery Sink] for the BigQuery integration.

The adaptor provides a flexible and extensible framework for data transformation and processing, including support for common data formats and in-transit data transformations.

[TIP]
====
This connector _doesn't_ require a Kafka instance.

Although the connector uses Kafka-related libraries, it operates entirely within {pulsar-short}.

Classes, properties, and configuration options that reference Kafka are translation points that map {pulsar-short} concepts to Kafka concepts in the connector.
====

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

[#pulsar-sink-connector-properties]
=== {pulsar-short} sink connector properties

include::pulsar-io:partial$connectors/sinks/pulsar-config-params.adoc[]

[#configs]
=== Kafka Connect adaptor properties (`configs`)

The properties in the `configs` section define how data is streamed from {pulsar-short} to BigQuery using the Kafka Connect adaptor.

For more information, see `https://github.com/apache/pulsar/blob/master/pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java[PulsarKafkaConnectSinkConfig.java]`.

[cols=4]
|===
|Name |Required |Default |Description

|`batchSize`
|No
|`16384`
|The maximum size, in bytes, of messages that the sink attempts to batch before flush.

|`collapsePartitionedTopics`
|No
|`false`
a|Whether to omit the `-partition-` suffix from the names of partitioned topics.
This determines how many BigQuery tables are created from partitioned topics:

* **`true`**: Collapse partitioned topics by removing the `-partition-` suffix from topic names.
All partitions of a partitioned topic are written to the same BigQuery table.
* **`false` (default)**: Maintain partitions by preserving the `-partition-` suffix when creating BigQuery tables from topic names.
Each partition of a partitioned topic is written to its own BigQuery table.

|`kafkaConnectorConfigProperties`
|No
|`{}` (empty map)
|A key-value map of <<kafkaConnectorConfigProperties,Kafka Connect BigQuery Sink properties>>.

|`kafkaConnectorSinkClass`
|Yes
|`""`
|The Kafka connector sink class to use.
For {product}, use `com.wepay.kafka.connect.bigquery.BigQuerySinkConnector` unless you have your own custom class.

|`lingerTimeMs`
|No
|`2147483647L`
|The duration, in milliseconds, that the sink attempts to batch messages before flush.

|`maxBatchBitsForOffset`
|No
|`12`
|Number of bits to use for the index of messages in a batch, which is translated into offsets (UUIDs).
Must be an integer between `0` and `20`.

If `0`, the behavior is disabled, and all messages in a batch have the same offset.

|`offsetStorageTopic`
|Yes
|`""`
|The {pulsar-short} topic where you want to store https://pulsar.apache.org/docs/4.1.x/tutorials-topic/[message offsets (UUIDs)].
This is an additional topic that helps track the connector's progress as messages are written to BigQuery.

|`sanitizeTopicName`
|Yes
|`false`
a|Whether to replace unprocessable characters in topic names with underscores.
For example, a {pulsar-short} topic named `persistent://a/b/topic` becomes `+persistent___a_b_topic+` when this property is `true`.

[IMPORTANT]
====
For BigQuery, you _must_ set `sanitizeTopicName` to `true` to prevent errors from invalid characters in topic names.
BigQuery table names can include only letters, numbers, and underscores, and the Kafka Connect BigQuery Sink doesn't sanitize topic names before creating BigQuery tables.

Be aware that this can cause naming collisions if two topics resolve to the same sanitized name.
For example, `topic_a` and `topic.a` are both sanitized as `topic_a`.
====

|`topic`
|Yes
|`""`
|The name of the {pulsar-short} topic that you want the sink to read from.
Only provide the topic name, not the whole address.

|`unwrapKeyValueIfAvailable`
|No
|`true`
a|Whether to unwrap `KeyValue<>` data if the message `value` is of type `Record<KeyValue<>>`:

* **`true` (default)**: For `Record<KeyValue<>>` data, extract `KeyValue<>` from the `Record` when writing to BigQuery.
* **`false`**: For `Record<KeyValue<>>` data, use the `Record` key (the entire `KeyValue<>` object) for writing to BigQuery.

|`useIndexAsOffset`
|No
|`true`
a|Whether to use the message index as the offset, instead of the message `sequenceId`:

* **`true` (default)**: Use the message index as the offset, if an index is available.
Otherwise, use the message `sequenceId`.
* **`false`**: Use the message `sequenceId` as the offset.

Requires `AppendIndexMetadataInterceptor` and `exposingBrokerEntryMetadataToClientEnabled=true` on https://pulsar.apache.org/docs/next/developing-binary-protocol/#broker-entry-metadata[brokers].

|`useOptionalPrimitives`
|No
|`false`
|{pulsar-short} schemas don't contain information about optional schemas, but Kafka schemas can include this information.
Set this property to `true` to force all primitive schemas to be optional when converting the {pulsar-short} schema to a Kafka schema.
|===

[#kafkaConnectorConfigProperties]
=== Kafka Connect BigQuery Sink properties (`kafkaConnectorConfigProperties`)

`kafkaConnectorConfigProperties` is a subproperty of `configs` that contains a map of configuration properties for the Kafka Connect BigQuery Sink.

After the Kafka Connect adaptor transforms the {pulsar-short} data into a Kafka-compatible format, the Kafka Connect BigQuery Sink writes the data to BigQuery according to the properties in `kafkaConnectorConfigProperties`.

Some of the Kafka Connect BigQuery Sink properties are the same as the Kafka Connect adaptor properties.
In some cases, the duplicate properties require matching values.
In other cases, you can use duplicate properties to perform additional data transformation or schema modification before writing to BigQuery.

For more information, see the https://docs.confluent.io/kafka-connectors/bigquery/current/kafka_connect_bigquery_config.html[Kafka Connect BigQuery Sink configuration reference] and `https://github.com/confluentinc/kafka-connect-bigquery/blob/master/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/config/BigQuerySinkConfig.java[BigQuerySinkConfig.java]`.

[cols=4]
|===
|Name |Required |Default |Description

|`allBQFieldsNullable`
|No
|`false`
|Whether the BigQuery schemas generated by the connector allow `null` values in all fields.

* **`false` (default)**: All fields in the BigQuery schemas are `REQUIRED`.
* **`true`**: No fields in the BigQuery schemas are `REQUIRED`.
All non-nullable Avro fields are translated as `NULLABLE` (or `REPEATED`, if arrays).

|`allowBigQueryRequiredFieldRelaxation`
|No
|`false`
|If `allBQFieldsNullable` is `false`, you can set this property to `true` to allow BigQuery schema updates to change `REQUIRED` fields to `NULLABLE`.
This only applies to schema updates that happen after initial table creation.

|`allowNewBigQueryFields`
|No
|`false`
a|Whether BigQuery schema updates can add fields:

* **`false` (default)**: Schema updates _cannot_ add fields to BigQuery tables.
* **`true`**: Schema updates _can_ add new fields to BigQuery tables.

This only applies to schema updates that happen after initial table creation.

|`allowSchemaUnionization`
|No
|`false`
a|Whether to enable schema unionization during schema updates:

* **`false` (default)**: The record of the last schema in a batch is used for any necessary table creation and schema update attempts.
* **`true`**: The existing table schema, if present, is unionized with new record schemas during schema updates.

For more information about this parameter, how it interacts with other parameters, and important considerations, see `allowSchemaUnionization` in the https://docs.confluent.io/kafka-connectors/bigquery/current/kafka_connect_bigquery_config.html[Kafka Connect BigQuery Sink configuration reference].

|`autoCreateBucket`
|No
|`true`
|Whether to automatically create the bucket if it doesn't exist.

|`autoCreateTables`
|No
|`false`
|Automatically create BigQuery tables if they don't already exist.

Tables are named after the sanitized {pulsar-short} topic names unless overridden by `topic2TableMap`.

|`avroDataCacheSize`
|No
|`100`
|The size of the cache to use when converting schemas from Avro to Kafka Connect.

|`bigQueryMessageTimePartitioning`
|No
|`false`
|Whether or not to use the message time when inserting records. Default uses the connector processing time.

|`bigQueryPartitionDecorator`
|No
|`true`
|Whether or not to append partition decorator to BigQuery table name when inserting records. Default is true. Setting this to true appends partition decorator to table name (e.g. table$yyyyMMdd depending on the configuration set for bigQueryPartitionDecorator). Setting this to false bypasses the logic to append the partition decorator and uses raw table name for inserts.

|`bigQueryRetry`
|No
|0
|The number of retry attempts made for a BigQuery request that fails with a backend error or a quota exceeded error.

|`bigQueryRetryWait`
|No
|1000
|The minimum amount of time, in milliseconds, to wait between retry attempts for a BigQuery backend or quota exceeded error.

|`clusteringPartitionFieldNames`
|No
|
|Comma-separated list of fields where data is clustered in BigQuery.

|`convertDoubleSpecialValues`
|No
|`false`
|Designates whether +Infinity is converted to Double.MAX_VALUE and whether -Infinity and NaN are converted to Double.MIN_VALUE to ensure successful delivery to BigQuery.

|`defaultDataset`
|Yes
|
|The default dataset to be used

|`deleteEnabled`
|No
|`false`
|Enable delete functionality on the connector through the use of record keys, intermediate tables, and periodic merge flushes. A delete will be performed when a record with a null value (a tombstone) is read. This feature will not work with SMTs that change the name of the topic.

|`enableBatchLoad` (Beta)
|No
|Not set
a|A subset of `topics` to be batch loaded through GCS to BigQuery.
If set, you can also set the following properties:

* `batchLoadIntervalSec`: The frequency, in seconds, that the connector attempts to run GCS to BigQuery load jobs.
* `gcsBucketName`: The name of the GCS bucket where blobs are staged for batch loading to BigQuery.

[IMPORTANT]
====
This is a beta feature that might have unexpected results or suboptimal performance.
====

|`includeKafkaData`
|No
|`false`
|Whether to include an extra block containing the original topic, offset, and partition information in the resulting BigQuery rows.

If `true`, you can use `kafkaDataFieldName` to specify the field name for this block.

|`intermediateTableSuffix`
|No
|`.tmp`
|A suffix that is used when creating intermediate tables from BigQuery destination tables.

The names of intermediate tables are constructed from the destination table name, the `intermediateTableSuffix`, and an additional suffix if needed for uniqueness.
For example, using the default suffix, a destination table named `bqTable` would have intermediate tables named `bqTable.tmp`, `bqTable.tmp_1`, `bqTable.tmp_2`, and so on.

|`keyfile`
|Yes
|Not set
|A string representation of Google credentials JSON, or the path to a Google credentials JSON file.

String format is required when creating this connector in the {astra-ui}.

|`keySource`
|Yes
|`FILE`
|If `keyfile` is a file path, set `keySource` to `FILE`.

If `keyfile` is a string, set `keySource` to `JSON`.

`JSON` is required when creating this connector in the {astra-ui}.

|`mergeIntervalMs`
|No
|`60_000L`
|The merge flush interval in milliseconds, if upsert/delete is enabled.

Set to `-1` to disable periodic flushing.

See also `mergeRecordsThreshold`.

|`mergeRecordsThreshold`
|No
|`-1`
|The number of records to write to an intermediate table before performing a merge flush, if upsert/delete is enabled.

The default is `-1`, which disables merge flushing based on record count.

See also `mergeIntervalMs`.

|`name`
|Yes
|`""`
|Must be the same as the `name` in the <<pulsar-sink-connector-properties>>.

|`project`
|Yes
|`""`
|The BigQuery project to write to.

|`queueSize`
|No
|`-1`
|The maximum size of the worker queue for BigQuery write requests before all topics are paused.

This is a soft limit; the queue size can exceed the maximum before topics are paused.
All topics resume after a flush, or when the queue size is less than half of the maximum.

The default is `-1`, which means the queue size is unlimited.

|`sanitizeTopics`
|Yes
|`false`
|In `kafkaConnectorConfigProperties`, you must set this property to `false`.

Topic names are sanitized by the Kafka Connect adaptor with `sanitizeTopicName` in `<<configs,configs>>`.

|`schemaRetriever`
|No
|`com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever`
|A class that can be used to create tables and update schemas automatically.

|`threadPoolSize`
|No
|`10`
|The size of the BigQuery write thread pool.
This determines the maximum number of concurrent writes to BigQuery.

|`timePartitioningType`
|No
|`DAY`
|The time partitioning type to use when creating tables: `DAY`, `HOUR`, `MONTH`, or `YEAR`.
This applies to new tables only; existing tables aren't altered to this partitioning type.

|`timestampPartitionFieldName`
|No
|Not set
|The name of the field in the message `value` that contains a timestamp to use for partitioning in BigQuery, and to enable timestamp partitioning on each table.

If empty, tables use ingestion-time partitioning.

|`topic2TableMap`
|No
|Not set
a|Optional map of topic names to table names formatted as comma-separated tuples, such as `topic1:table1,topic2:table2,topic3:table3`.

[IMPORTANT]
====
If you use this property, you must use the sanitized topic names, not the original {pulsar-short} topic names.
Because `sanitizeTopicName` is `true` in `<<configs,configs>>`, the Kafka Connect BigQuery Sink receives sanitized topic names from the Kafka Connect adaptor.
For example, a {pulsar-short} topic named `persistent://a/b/c-d` must be mapped with the sanitized name `+persistent___a_b_c_d+`.
====

|`topics`
|Yes
|`""`
|Must be the same as the `topic` in the <<pulsar-sink-connector-properties>>.

|`upsertEnabled`
|No
|`false`
|Whether to enable upsert functionality on the connector by using record keys, intermediate tables, and periodic merge flushes.
Row-matching is performed based on the contents of record keys.
This feature doesn't work with SMTs that change the name of the topic.
|===