:connectorName: jdbc-clickhouse
:connectorType: jdbc-clickhouse
:attribute-missing: skip
:slug: clickhouse-sink-connector
:page-tag: jdbc,clickhouse,sink-connector

= JDBC Clickhouse Sink Connector for {product_name}

ClickHouse is an open-source column-oriented database management system for online analytical processing that allows users to generate analytical reports using SQL queries in
real-time. 

[NOTE]
====
Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses the https://github.com/ClickHouse/clickhouse-jdbc[Clickhouse 0.3.2 library] to interact with Clickhouse.
====

== Get Started

include::partial$connectors/sinks/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sinks/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sinks/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sinks/astra.csv[]
|===

=== Clickhouse (configs)

These values are provided in the "configs" area.

The Astra Streaming JDBC Clickhouse sink connector supports all configuration properties provided by Apache Pulsar. Please refer to the https://pulsar.apache.org/docs/io-jdbc-sink#property[connector
properties^]
for a complete list.

== What's next?

Learn more about Clickhouse's features and capabilities on https://clickhouse.com/[their site^].

Learn more about Apache Pulsar's JDBC sink connector https://pulsar.apache.org/docs/io-jdbc-sink[here^].