= JDBC Clickhouse
:connectorType: jdbc-clickhouse

//capitalization of Clickhouse?
The JDBC-ClickHouse sink connector reads messages from {pulsar} topics and writes them to JDBC-ClickHouse systems.

ClickHouse is an open-source column-oriented database management system for online analytical processing that allows users to generate analytical reports using SQL queries in
real-time.

{product} currently supports {pulsar-reg} {pulsar-version}, which uses the https://github.com/ClickHouse/clickhouse-jdbc[Clickhouse 0.3.2 library] to interact with Clickhouse.

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} sink connector parameters

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== JDBC Clickhouse sink connector parameters (`configs`)

Set these parameters in the `configs` section of the connector configuration.

The {product} JDBC Clickhouse sink connector supports all configuration properties provided by {pulsar}. Please refer to the https://pulsar.apache.org/docs/io-jdbc-sink#property[connector
properties]
for a complete list.

== What's next?

Learn more about Clickhouse's features and capabilities on https://clickhouse.com/[their site].

Learn more about {pulsar-short}'s JDBC sink connector https://pulsar.apache.org/docs/io-jdbc-sink[here].