:connectorName: jdbc-mariadb
:connectorType: jdbc-mariadb
:attribute-missing: skip
:slug: mariadb-sink-connector
:page-tag: jdbc,mariadb,sink-connector

= JDBC MariaDB Sink Connector for {product_name}

MariaDB is the open source relational database loved by developers all over the world. Created by MySQL’s original developers, MariaDB is compatible with MySQL and guaranteed to stay open source forever. MariaDB powers some of the world’s most popular websites such as Wikipedia and WordPress.com. It is also the core engine behind banking, social media, mobile and e-commerce sites worldwide. MariaDB Connector/J is a Type 4 JDBC driver. It was developed specifically as a lightweight JDBC connector for use with MariaDB and MySQL database servers. It was originally based on the Drizzle JDBC code with numerous additions and bug fixes. Learn more about MariaDB on https://mariadb.org/[their site^].

Read more about Apache Pulsar's JDBC sink connector https://pulsar.apache.org/docs/io-jdbc-sink[here^].

[NOTE]
====
Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses the https://mariadb.com/kb/en/about-mariadb-connector-j/[MariaDB Connector/J 2.7.5 library] to interact with MariaDB.
====

== Get Started

include::partial$connectors/sinks/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sinks/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sinks/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sinks/astra.csv[]
|===

=== MariaSQL (configs)

These values are provided in the "configs" area.

The Astra Streaming JDBC MariaDB sink connector supports all configuration properties provided by Apache Pulsar. Please refer to the https://pulsar.apache.org/docs/io-jdbc-sink#property[connector
properties^]
for a complete list.