:connectorName: kafka-sink
:connectorType: kafka
:attribute-missing: skip
:slug: kafka-sink-connector
:page-tag: kafka,sink-connector

= Kafka Sink Connector for {product_name}

Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications. 

[NOTE]
====
Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses the https://github.com/apache/kafka/tree/2.7[Kafka 2.7.2 library] to interact with
Kafka.
====

== Get Started

include::partial$connectors/sinks/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sinks/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sinks/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sinks/astra.csv[]
|===

=== Kafka (configs)

These values are provided in the "configs" area.

The Astra Streaming Kafka sink connector supports all configuration properties provided by Apache Pulsar. Please refer to the https://pulsar.apache.org/docs/io-kafka-sink#property[connector properties^] for a complete list.

== What's next?

Learn more about Kafka’s features and capabilities on https://kafka.apache.org/[their site^].

Learn more about Apache Pulsar's Kafka sink connector https://pulsar.apache.org/docs/io-kafka-sink[here^].