= Kafka
:connectorType: kafka

The Kafka sink connector reads messages from {pulsar} topics and writes them to Kafka systems.

Apache Kafka(R) is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.

{product} currently supports {pulsar-reg} {pulsar-version}, which uses the https://github.com/apache/kafka/tree/2.7[Kafka 2.7.2 library] to interact with
Kafka.

== Create the connector

include::partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::partial$connectors/sinks/manage.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== Astra Streaming

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== Kafka (`configs`)

These values are provided in the "configs" area.

The {product} Kafka sink connector supports all configuration properties provided by {pulsar-short}. Please refer to the https://pulsar.apache.org/docs/io-kafka-sink#property[connector properties] for a complete list.

== What's next?

Learn more about Kafka’s features and capabilities on https://kafka.apache.org/[their site].

Learn more about {pulsar-short}'s Kafka sink connector https://pulsar.apache.org/docs/io-kafka-sink[here].