:connectorName: kinesis-sink
:connectorType: kinesis
:attribute-missing: skip
:slug: kinesis-sink-connector
:page-tag: kinesis,sink-connector

= Kinesis Sink Connector for {product_name}

Amazon Kinesis collects, processes, and analyzes real-time streaming data for timely insights and quick reactions to new information. 

Amazon Kinesis cost-effectively processes streaming data at any scale, and offers the flexibility to choose the tools that best suit your application's requirements. 

The Amazon Kinesis Client Library for Java (Amazon KCL) enables Java developers to easily consume and process data from Amazon Kinesis. 

[NOTE]
====
Astra Streaming currently supports Apache Pulsar {pulsar_version}, which uses the https://github.com/awslabs/amazon-kinesis-client[Amazon Kinesis 2.2.8 library^] and the https://github.com/aws/aws-sdk-java[AWS Java SDK 0.14.0 library^] to interact with Kinesis.
====

== Get Started

include::partial$connectors/sinks/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sinks/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sinks/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sinks/astra.csv[]
|===

=== Kinesis (configs)

These values are provided in the "configs" area.

The Astra Streaming Kinesis sink connector supports all configuration properties provided by Apache Pulsar. Please refer to the https://pulsar.apache.org/docs/io-kinesis-sink#property[connector properties^] for a complete list.

== What's next?

Learn more about Kinesis’s features and capabilities on https://aws.amazon.com/kinesis/[their site^].

Learn more about Apache Pulsar's Kinesis sink connector https://pulsar.apache.org/docs/io-kinesis-sink[here^].