:connectorName: snowflake-sink
:connectorType: snowflake
:attribute-missing: skip
:slug: snowflake-sink-connector
:page-tag: snowflake,sink-connector

= Snowflake Sink Connector for {product_name}

A Snowflake database is where an organization's uploaded structured and semi-structured data sets are held for processing and analysis. 

Snowflake automatically manages all parts of the data storage process, including organization, structure, metadata, file size, compression, and statistics. 

== Get Started

include::partial$connectors/sinks/get-started.adoc[]

== Managing the Connector

include::partial$connectors/sinks/manage.adoc[]

== Monitoring the Connector

include::partial$connectors/sinks/monitoring.adoc[]

== Connector Reference

There are two sets of parameters that support sink connectors.

=== Astra Streaming

[%header,format=csv,cols="2,1,1,3"]
|===
include::example$connectors/sinks/astra.csv[]
|===

=== Snowflake (configs)

These values are provided in the "configs" area.

The Astra Streaming Snowflake sink connector supports all configuration properties provided by DataStax. Please refer to the https://github.com/datastax/snowflake-connector#configuration[connector
properties^] for a complete list.

== What's next?

Learn more about Snowflake’s features and capabilities on https://www.snowflake.com/en/[their site^].

Learn more about DataStax Apache Pulsar Snowflake sink connector https://github.com/datastax/snowflake-connector[here^].