= Snowflake
:connectorType: snowflake

The Snowflake sink connector reads messages from {pulsar} topics and writes them to Snowflake systems.

A Snowflake database is where an organization's uploaded structured and semi-structured data sets are held for processing and analysis.

Snowflake automatically manages all parts of the data storage process, including organization, structure, metadata, file size, compression, and statistics.

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} sink connector parameters

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== Snowflake sink connector parameters (`configs`)

Set these parameters in the `configs` section of the connector configuration.

The {product} Snowflake sink connector supports all configuration properties provided by {company}. Please refer to the https://github.com/datastax/snowflake-connector#configuration[connector
properties] for a complete list.

== What's next?

Learn more about Snowflake’s features and capabilities on https://www.snowflake.com/en/[their site].

Learn more about {company} {pulsar} Snowflake sink connector https://github.com/datastax/snowflake-connector[here].