= Snowflake
:connectorType: snowflake

A https://www.snowflake.com/en/[Snowflake] database ingests structured and semi-structured datasets for processing and analysis.
Snowflake automatically manages all parts of the data storage process, including organization, structure, metadata, file size, compression, and statistics.

The Snowflake sink connector reads messages from {pulsar} topics and writes them to Snowflake databases.

== Create the connector

include::pulsar-io:partial$connectors/sinks/get-started.adoc[]

== Edit the connector

include::pulsar-io:partial$connectors/sinks/edit.adoc[]

== Manage the connector

include::pulsar-io:partial$connectors/sinks/manage.adoc[]

== Connector configuration reference

include::pulsar-io:partial$connectors/connector-params-intro.adoc[]

=== {pulsar-short} sink connector parameters

include::pulsar-io:partial$connectors/sinks/astra-config-params.adoc[]

[#configs]
=== Snowflake sink connector parameters (`configs`)

Set these parameters in the `configs` section of the connector configuration.

For all supported parameters, examples, and exceptions, see the https://github.com/datastax/snowflake-connector[{company} Snowflake connector GitHub repository].